=== slac-epics/ip231/extensions/src/ChannelArchiver/ExampleSetup/ArchiveDaemon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the ArchiveDaemon Configuration -->
<!ELEMENT daemon (port, mailbox?, engine*)>

<!ELEMENT port   (#PCDATA)>  <!-- TCP port number    -->
<!ELEMENT mailbox (#PCDATA)> <!-- /path              -->

<!ELEMENT engine
          (desc, port, config, restart?, dataserver?)>
<!ATTLIST engine directory CDATA #REQUIRED>

<!ELEMENT desc   (#PCDATA)> <!-- Text               -->
<!ELEMENT config (#PCDATA)> <!-- path               -->

<!ELEMENT restart (#PCDATA)> <!-- path               -->
<!ATTLIST restart
          type (weekly|daily|hourly|timed) #REQUIRED>
<!-- weekly  Mo|Tu|...|Su HH:MM
     daily   HH:MM
     hourly  (double) hours
     timed   HH:MM/HH:MM  
             (start/duration)
  -->

<!ELEMENT dataserver (host?)>
<!ELEMENT host (#PCDATA)>

=== slac-epics/ip231/extensions/src/ChannelArchiver/ExampleSetup/ArchiveDaemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE daemon SYSTEM "ArchiveDaemon.dtd">
<daemon>
    <port>4900</port>
    <mailbox>/arch/xfer</mailbox>
    <engine directory='llrf'>
        <desc>LLRF</desc>
        <port>4901</port>
        <config>llrf-group.xml</config>
        <restart type='weekly'>We 10:20</restart>
        <dataserver><host>web2</host></dataserver>
    </engine>
    <!-- Typically, more entries follow:
    <engine directory='hprf'>
        ...
    </engine>
     -->
</daemon>
