=== slac-epics/ip231/extensions/src/ChannelArchiver/ExampleSetup/archiveconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the archiveconfig -->
<!ELEMENT archiveconfig (root, serverconfig, mailbox, daemon*)>

<!ELEMENT root (#PCDATA)>
<!ELEMENT serverconfig (#PCDATA)>
<!ELEMENT mailbox (#PCDATA)>

<!ELEMENT daemon (run?, desc?, port?, dataserver?, engine*)>
<!ATTLIST daemon directory CDATA #REQUIRED>

<!ELEMENT dataserver (current_index?, index?, host?)>
<!ELEMENT current_index (#PCDATA)>
<!ATTLIST current_index key CDATA #REQUIRED>
<!ELEMENT index (#PCDATA)>
<!ATTLIST index type (serve|list|binary) #REQUIRED>
<!ATTLIST index key CDATA #IMPLIED>
<!ATTLIST index file CDATA #IMPLIED>
<!ELEMENT host (#PCDATA)>

<!ELEMENT engine (run?, desc?, port?, restart?, dataserver?)>
<!ATTLIST engine directory CDATA #REQUIRED>

<!ELEMENT run (#PCDATA)> <!-- hostname where daemon or engine should run. 'false' for: don't run at all -->
<!ELEMENT desc (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT restart (#PCDATA)>
<!ATTLIST restart type (weekly|daily|hourly|timed) #REQUIRED>
<!-- weekly  Mo|Tu|...|Su HH:MM
     daily   HH:MM
     hourly  (double) hours
     timed   HH:MM/HH:MM  
             (start/duration)
  -->

=== slac-epics/ip231/extensions/src/ChannelArchiver/ExampleSetup/archiveconfig.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE archiveconfig SYSTEM "archiveconfig.dtd">
<archiveconfig>
  <root>/arch</root>

  <serverconfig>/var/www/serverconfig.xml</serverconfig>

  <mailbox>/arch/xfer</mailbox>

  <daemon directory='RF'>
    <run>archive1</run>
    <desc>RF</desc>
    <port>4900</port>
    <dataserver>
      <index type='binary' key='10'>RF</index>
      <host>web2</host>
    </dataserver>
    <engine directory='llrf'>
      <run>archive1</run>
      <desc>LLRF</desc>
      <port>4901</port>
      <restart type='weekly'>We 10:20</restart>
      <dataserver>
        <current_index key='4901'>llrf</current_index>
        <index type='binary'>LLRF data</index>
        <host>web2</host>
      </dataserver>
    </engine>
  </daemon>
</archiveconfig>
